#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.2.15.201:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: zhdt
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
