#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zhdtedu.riverchiefs.bean,com.zhdtedu.system.bean
  mapperLocations: classpath:com/zhdtedu/riverchiefs/dao/mapper/*.xml,classpath:com/zhdtedu/system/dao/mapper/*.xml
---

#开发配置172.2.15.201localhost
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://106.13.53.183:3306/douyin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #配置JSP视图
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
      #控制台打印sql语句
        logging:
          level:
            com.ming.ssm.mapper: debug
